### ISSUE TITLE
Error 310: Rendered more hooks than during the previous render

### ISSUE THREAD

**Issue by Kovah** [Kovah/Tradefinder#23]
When changing values to result in a successful new trade, the app crashes with error 310 "Rendered more hooks than during the previous render" caused by https://github.com/Kovah/Tradefinder/blob/main/src/app/helper.js#L5

More info:
I am formatting numbers in the app using a helper function. This helper function pulls the global app configuration from the state where the number format is stored.

```js
import { useSelector } from 'react-redux';
import { getOptions } from '../features/options/OptionsSlice';

export function formatNumber (number) {
  // this line crashed the app
  const options = useSelector(getOptions);

  const formatted = new Intl.NumberFormat([options.numberFormat, 'en-US'], {
    maximumSignificantDigits: 2
  }).format(number);

  return formatted.toString();
}
```

Example usage of the formatNumber() helper: https://github.com/Kovah/Tradefinder/blob/main/src/features/trading/Trades.js#L70

**Comment by ffraenz** [comment]
Hi @Kovah! As the error message states React assumes that you always call the same number of hooks in a React component. Note, that you use `useSelector` in `formatNumber`, which makes `formatNumber` a hook, too. In your example usage case you call `formatNumber` when mapping `possibleTrades` elements. The number of these elements may change between renders (e.g. in a successful new trade, I guess) leading to this error.

Possible solution: Add `numberFormat` as a second parameter to `formatNumber` and retrieve this value once at the top of your React component via `useSelector` to forward it to the utility function call. This way `formatNumber` is no hook anymore and can be called with no constraints.

**Comment by Kovah** [comment]
I moved getting the option out of the helper function and it works. Not really cool, but there seems to be no other option right now. 🤷 
Thanks @ffraenz!

**Comment by ffraenz** [comment]
These assumptions feel strange in occasions like these but at the end they bring us the big performance optimizations we get for free with React & Redux ✨
